---
- hosts: "masters"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
   
   - name: Installing unzip
     apt: 
       name:
         - unzip
       state: present

   - name: Download repository
     get_url:
     url: https://github.com/SmartGuyy/p13_oc_pods/archive/master.zip
     dest: /tmp
     mode: '0440'

   - name: Unzip repository
     become_user: ubuntu
     become_method: sudo
     become: yes
     command: "{{ item }}"
     with_items: 
        - unzip /tmp/master.zip
        - rm master.zip

   - name: Creating docker local registry, building images and pushing it
     become_user: ubuntu
     become_method: sudo
     become: yes
     command: "{{ item }}"
     with_items: 
        - docker run -d -p 5000:5000 --restart=always --name registry registry:2
        - docker build -t localhost:5000/mysql-server -f /tmp/p13_oc_pods-master/Alpine_MySQL-server/Dockerfile /tmp/p13_oc_pods-master/Alpine_MySQL-server
        - docker push localhost:5000/mysql-server
        - docker build -t localhost:5000/php_mysql-client -f /tmp/p13_oc_pods-master/Alpine_PHP_MySQL-client/Dockerfile /tmp/p13_oc_pods-master/Alpine_PHP_MySQL-client 
        - docker push localhost:5000/php_mysql-client

   - name: Applying pod configuration to create them
     become_user: ubuntu
     become_method: sudo
     become: yes
     command: "{{ item }}"
     with_items: 
        - kubectl apply -f /tmp/p13_oc_pods-master/Alpine_MySQL-server/POD_MySQL-server.yaml
        - kubectl apply -f /tmp/p13_oc_pods-master/Alpine_PHP_MySQL-client/POD_PHP-MySQL.yaml
   
   - pause: seconds=30


...
