apiVersion: v1
kind: Pod
metadata:
  name: php-mysql
spec:
  containers:
  - name: php-mysql
    image: localhost:5000/php-mysql
    # Just spin & wait forever
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]